updated to Gatsby version
filetrust/k8-electron-react pull request #29
Opened 2020-09-11 18:10 UTC by GiuseMSD

2020-09-12 23:38 UTC, DinisCruz requested changes

2020-09-12 23:38 UTC, DinisCruz commented on README.md
> +Made with ♥ by João Pedro Schmitz
This is not correct since you removed the previous content

2020-09-12 23:38 UTC, DinisCruz commented on public/index.html
> +<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta na
Don’t publish files inside the ‘public’ folder

2020-09-14 15:45 UTC, GiuseMSD commented on public/index.html
> +<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta na
@DinisCruz, It's published by Gatsby runtime cli to be processed. What do you mean not to publish?

2020-09-14 16:33 UTC, closed without merging